# This is a value override file for cluster-api-openstack Helm chart in asset-*/taco-helm/cluster-api-openstack

cluster_name: taco-mgmt

kube:
  network:
    serviceDomain: taco-mgmt

etcd:
   election_timeout: 10000

openstack:
  cloud: # This is from the clouds.yaml
    name: zugwan
    conf:
      Global:
        auth-url: http://keystone.openstack.svc.cluster.local:80/v3
        username: zugwan
        password: djawnrhks
        tenant-name: zugwan
        domain-name: default
        region: RegionOne
    cacert: "\n"
  dns_name_servers:
  - 192.168.95.11
  external_network_id: e98e5ab1-1775-46bb-8a7b-ae1ced2950ff

# SSH bastion Host
bastion:
  enabled: true
  flavor: m1.large
  image: ubuntu-2004-kube-v1.20.2-2021-03-05
  ssh_keyname: capo

# Kubernets Master Nodes
masters:
  ssh_keyname: capo
  # This is for boot from volume
  root_volume:
    diskSize: 100
    sourceType: snapshot
    sourceUUID: 5b516e3d-9340-4fa9-a2f0-489d0bd0182c

# Kubernets Worker Nodes
workers:
  replicas: 3
  ssh_keyname: capo
  failure_domain: r06
  # This is for boot from volume
  root_volume:
    diskSize: 100
    sourceType: snapshot
    sourceUUID: 5b516e3d-9340-4fa9-a2f0-489d0bd0182c
